# Build settings
markdown:           kramdown
permalink:          pretty


# Dependencies

markdown:           kramdown
highlighter:        pygments
gems:               [jekyll-paginate]

# Permalinks
permalink:          pretty

# Setup
title:              "Minimal Computing"
tagline:
description:        "a working group of GO::DH"

email:              mincomp@lists.globaloutlookdh.org


paginate:           5
layout:             blog-post

# Custom vars
version:            2.0.0

